src/game/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^play', views.PlayView.as_view(), name='play'),
    url(r'^form', views.check_rule, name='form'),
    url(r'^score', views.ScoreView.as_view(), name='score'),
]

src/wordchain/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from decorator_include import decorator_include

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^game/', decorator_include(login_required, 'game.urls', namespace='game')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', 'wordchain.views.register', name='register'),
    url(r'^accounts/logout/', 'wordchain.views.logout', name='logout'),
]

src/game/models.py
from django.db import models

# Create your models here.

class History(models.Model):
    userId = models.CharField(max_length=50)
    text = models.CharField(max_length=50)
    updateDate = models.DateTimeField('date published')
    
class Score(models.Model):
    userId = models.CharField(max_length=50)
    score = models.IntegerField(default=0)
    updateDate = models.DateTimeField('date published')
    

src/game/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic import DetailView
from django import forms
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
import datetime
from .gameRule import Game, GameScore

from .myDictionary import MyDictionary, myDictionary
from .models import History, Score

# Create your views here.


class IndexView(generic.ListView):
    template_name = 'game/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return

class ScoreView(generic.ListView):
    template_name = 'game/scoreboard.html'
    context_object_name = 'Score'
    
    def get_queryset(self):
        return Score.objects.order_by('-score')

gameRule = Game()
gameScore = GameScore()

class PlayView(generic.ListView):
    template_name = 'game/play.html'
    context_object_name = 'History'

    def get_queryset(self):
        gameScore.init(self.request.user)
        
        errWord = self.request.GET.get('errWord')
        errType = self.request.GET.get('errType')
        print('request: ', errWord, ", ", errType)
        
        if gameRule.isObserverMode(self.request.user):
            return {'obj':History.objects.order_by('-updateDate')[0:10], 'errWord':errWord, 'errType':errType, 'inObserverMode':True}
        else:
            return {'obj':History.objects.order_by('-updateDate')[0:10], 'errWord':errWord, 'errType':errType, 'inNormalMode':True}

def check_rule(request):
    gameScore.init(request.user)
        
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        answer = request.POST['answer']
        
        if len(answer) <= 0:
            return HttpResponseRedirect('play?errWord='+ ' ' +'&errType='+'Empty')
        
        # word chain validation check
        lastWords = History.objects.order_by('-updateDate')
        if len(lastWords) > 0:
            lastWord = lastWords[0]
            lastLetter = lastWord.text[-1]
            # print(lastWord, " : ", lastLetter)
            
            if lastLetter != answer[0]:
                # print('letterMissMatch: ', lastLetter, ", ", answer)
                if gameScore.update(request.user, gameScore.PENALTY_LASTLETTERMISSMATCH):
                    return HttpResponseRedirect('play?errWord='+ answer +'&errType='+'letterMissMatch')
                else:
                    return HttpResponseRedirect('play')
        
        matchedList = History.objects.filter(text=answer)
        if len(matchedList) > 0:
            # print('matchedList: ', matchedList[0].updateDate)
            if gameScore.update(request.user, gameScore.PENALTY_ALREADYEXIST):
                return HttpResponseRedirect('play?errWord='+answer+'&errType='+'AlreadyExist')
            else:
                return HttpResponseRedirect('play')

        if not myDictionary.isExist(answer):
            # print('NotInDic: ', answer)
            if gameScore.update(request.user, gameScore.PENALTY_NOTINDIC):
                return HttpResponseRedirect('play?errWord='+answer+'&errType='+'NotInDic')
            else:
                return HttpResponseRedirect('play')

        if gameRule.isNoMoreWord(answer):
            print(request.user)
            gameRule.restart()
            return HttpResponseRedirect('play')

        # db write
        p = History(text=answer, userId=request.user, updateDate= str(datetime.datetime.now()))
        p.save()
        
        # score update
        gameScore.update(request.user, gameScore.ADD_CORRECT)

        return HttpResponseRedirect('play')
        
    # if a GET (or any other method) we'll create a blank form
    else:
        return render(request, 'play.html', {'form': forms.Form})

src/wordchain/views.py
from django.views import generic
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'index.html'
    
    def get_queryset(self):
        return
    
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect("/game")
    else:
        form = UserCreationForm()
    return render(request, "registration/register.html", {
        'form': form,
    })
    
def logout(request):
    logout(request)

src/game/templates/game/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>

        <!--http://threejs.org/docs/index.html#Manual/Introduction/Creating_a_scene-->
        <!--http://stemkoski.github.io/Three.js/#hello-world-->
        <!--http://jafty.com/blog/tag/three-js-rotate-text-by-center/-->

        <link rel="stylesheet" type="text/css" href="{% static 'game/style.css' %}" />
        <style type="text/css">
            canvas { width: 500px; height: 500px }
        </style>
    </head>

    <body>
        <!--<script src="http://threejs.org/build/three.min.js"></script>-->
        <script src="https://stemkoski.github.io/Three.js/js/Three.js"></script>
        <script src="https://stemkoski.github.io/Three.js/js/Stats.js"></script>
        <script src="https://stemkoski.github.io/Three.js/js/Detector.js"></script>
        <script src="https://stemkoski.github.io/Three.js/js/OrbitControls.js"></script>
        
        <script src="https://stemkoski.github.io/Three.js/fonts/helvetiker_bold.typeface.js"></script>
        <script src="https://stemkoski.github.io/Three.js/fonts/helvetiker_regular.typeface.js"></script>

        <script type="text/javascript">
            var scene = new THREE.Scene();
            // var camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );
            var camera = new THREE.PerspectiveCamera( 75, 500/500, 0.1, 1000 );

            // var renderer = new THREE.WebGLRenderer();
            var renderer = window.WebGLRenderingContext ? new THREE.WebGLRenderer() : new THREE.CanvasRenderer(); // Fallback to canvas renderer, if necessary.
            // renderer.setSize( window.innerWidth, window.innerHeight);
            renderer.setSize( 500, 500);
            document.body.appendChild( renderer.domElement );
            
            var pointLight = new THREE.PointLight(0xFFFFFF); // Set the color of the light source (white).
            pointLight.position.set(50, 50, 50); // Position the light source at (x, y, z).
            scene.add(pointLight); // Add the light source to the scene.

// 			var geometry = new THREE.BoxGeometry( 1, 1, 1 );
// 			var material = new THREE.MeshBasicMaterial( { color: 0x00ff00} );
// 			var cube = new THREE.Mesh( geometry, material );
// 			scene.add( cube );

            var materialFront = new THREE.MeshBasicMaterial( { color: 0xff0000 } );
            var materialSide = new THREE.MeshBasicMaterial( { color: 0x000088 } );
            var materialArray = [ materialFront, materialSide ];
			var textGeom = new THREE.TextGeometry( "Word Chain", 
        	{
                size: 30, height: 4, curveSegments: 3,
                font: "helvetiker", weight: "bold", style: "normal",
                bevelThickness: 1, bevelSize: 2, bevelEnabled: true,
                material: 0, extrudeMaterial: 1
        	});
        	
            var textMaterial = new THREE.MeshFaceMaterial(materialArray);
            
            textGeom.computeBoundingBox();
            var textWidth = textGeom.boundingBox.max.x - textGeom.boundingBox.min.x;
            var textHeight = textGeom.boundingBox.max.y - textGeom.boundingBox.min.y;

            var textMesh = new THREE.Mesh(textGeom, textMaterial );
            textMesh.position.set( -0.5 * textWidth, -0.5 * textHeight, 0 );

            pivot = new THREE.Object3D();
            pivot.add( textMesh );
            scene.add( pivot );

            scene.add(pivot);

			camera.position.z = 200;

			var render = function () {
				requestAnimationFrame( render );

				// pivot.rotation.x += 0.02;
				pivot.rotation.y += 0.02;

				renderer.render(scene, camera);
			};

			render();            
        </script>        

    {% if latest_question_list %}
    	<p>ID {{ user.username }}</p>
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'game:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
        <form method="post" action="{% url 'django.contrib.auth.views.logout' %}">
        	{% csrf_token %}
    		<input type="submit" value="logout" />    
    	</form>
    {% else %}
        <h2><a href="{% url 'game:play' %}" id="gameplay">Go To Game Page</a></h2>
        <h2><a href="{% url 'game:score' %}" id="gamescore">Show Ranking</a></h2>
        <h2><a href="{% url 'logout' %}?next={% url 'game:index' %}" id="logout">Logout</a></h2>
    {% endif %}
    </body>
</html>

src/game/templates/game/play.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'game/style.css' %}" />
        <style type="text/css">
            /*https://css-tricks.com/snippets/css/style-placeholder-text/*/
            ::-webkit-input-placeholder {
               color: red;
            }
            
            :-moz-placeholder { /* Firefox 18- */
               color: red;  
            }
            
            ::-moz-placeholder {  /* Firefox 19+ */
               color: red;  
            }
            
            :-ms-input-placeholder {  
               color: red;  
            }
        </style>
    </head>
    <body>
        <!--http://www.html.am/html-codes/scrollboxes/scrollbox-border.cfm-->
        
        <table style="width:500px;overflow:scroll;padding:5px;border:6px double #DEBB07;">
            {% for history in History.obj.all reversed %}
            <tr>
                <td style="color:hsl(240,100%,50%);">{{ history.text }}</td> <td>{{ history.userId }}</td> <td>{{ history.updateDate|date:'Y-m-d H:i:s' }}</td>
            </tr>
            {% endfor %}
        </table>
        
        {% if History.inNormalMode %}
            <form method="post" action="{% url 'game:form' %}">
                {% csrf_token %}
                <input type="text" name="answer"
            
            {% if History.errWord %}
                placeholder="{{ History.errWord }} , {{ History.errType }}")
            {% endif %}
                 autofocus />
                 
                <input type="submit" name="Submit"/>
            </form>
        {% else %}
            <h2 style="color:red;">You are in Observer mode !!!</h2>
        {% endif %}
        
        <h2><a href="{% url 'game:index' %}">Go To Main Page</a></h2>
    </body>
</html>

src/game/templates/game/scoreboard.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <style>
            body {
                font-family: Helvetica;
            }
            svg {
                width: 500px;
                height: 500px;
            }
            .top-level {
                font-size: 13px;
                font-style: italic;
                text-transform: uppercase;
                float: left;
            }
            .age-lebel {
                text-align: right;
                font-weight: bold;
                width: 90px;
                padding-right: 10px;
            }
            .clearfix {
                clear: both;
            }
            .bar {
                fill: DarkSlateBlue;
            }
            .bar-label {
                text-anchor: end;
            }
            .axis-label {
                text-anchor: middle;
                font-size: 13px;
            }
            
            div.tooltip {
              position: absolute;	
              text-align: center;	
              width: 100px;	
              height: 28px;		
              padding: 2px;	
              font: 12px sans-serif;	
              background: lightsteelblue;	
              border: 0px;					
              border-radius: 8px;
            }
        </style>
    </head>
    <body>
        <script src="https://d3js.org/d3.v3.min.js"></script>
        
        <script>
            var dataName = [{% for score in Score.all %} "{{ score.userId }}", {% endfor %}];
            var dataScore = [{% for score in Score.all %} {{ score.score }}, {% endfor %}];
            var dataDate = [{% for score in Score.all %} "{{ score.updateDate }}", {% endfor %}];
            // var dataText = [{% for score in Score.all %} "{{ score.userId }} : {{ score.updateDate }}", {% endfor %}];
            
            var width = 400,
                leftMargin = 100,
                topMargin = 30,
                barHeight = 20,
                barGap = 20,
                tickGap = 5,
                tickHeight = 10,
                barSpacing = barHeight + barGap,
                scaleFactor = width / Math.max(...dataScore),
                translateText = "translate(" + leftMargin + "," + topMargin + ")",
                scaleText = "scale(" + scaleFactor + ",1)";
        
            var ulBody = d3.select("body");
            ulBody.append("h2").text("-- SCORE --");
            
            // http://bl.ocks.org/d3noob/c37cb8e630aaef7df30d
            // Define 'div' for tooltips
            var div = d3.select("body")
            	.append("div")  // declare the tooltip div 
            	.attr("class", "tooltip")              // apply the 'tooltip' class
            	.style("opacity", 0);                  // set the opacity to nil
            
            var svg = ulBody.append("svg");
            var barGroup = svg.append("g")
                .attr("transform", translateText + " " + scaleText)
                .attr("class", "bar");
                
            var mouseCheck = 0;
            
            barGroup.selectAll("rect").data(dataScore)
                .enter().append("rect")
                .attr("x",0)
                .attr("y", function(d,i) {return i*barSpacing})
                .attr("width", 0)
                .attr("height", barHeight)
        	    .on("mouseover", function() {
        	        mouseCheck  = 1;
        			div.transition()
        				.duration(200)
        				.style("opacity", .9);
        	    })
        		.on("mouseout", function() { 
        		    mouseCheck = 0;
                    div.transition()
        				.duration(500)
        				.style("opacity", 0);
        		})
        		.on("mousemove", function(d, i) {
        		    if(mouseCheck == 0)
        		        return;
        		        
        			div	.html("score: " + dataScore[i] + "</br>" + dataDate[i].substr(8))
        				.style("left", (d3.event.pageX) + "px")
        				.style("top", (d3.event.pageY - 28) + "px");
        			});

            barGroup.selectAll("rect").data(dataScore)
                .transition().duration(500)
                .attr("width", function(d) {return d});

            var barLabelGroup = svg.append("g")
                .attr("transform", translateText)
                .attr("class", "bar-label");
                
            barLabelGroup.selectAll("text")
                .data(dataName)
                .enter().append("text")
                .attr("x", function(d) {return d*scaleFactor})
                .attr("y", function(d,i) {return i*barSpacing - 5})
                .text(function(d) {return d});
                
        </script>
        
        <h2><a href="{% url 'game:index' %}">Go To Main Page</a></h2>
    </body>
</html>

<!--<link rel="stylesheet" type="text/css" href="{% static 'game/style.css' %}" />-->

src/templates/index.html
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <ul>
            <li><a href='game' id="play">Play Wordchain</a></li>
            <li><a href='admin' id="admin">Admin</a></li>
        </ul>
    </body>
</html>